CREATE TABLE dbo.UsersTable
(
  UserID VARCHAR(255) NOT NULL PRIMARY KEY,
  Username VARCHAR(255) UNIQUE NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  Password VARCHAR(max) NOT NULL,
  Avatar VARCHAR(255),
);
GO