export const FETCH_ANSWERS_REQUEST = "FETCH_ANSWERS_REQUEST";
export const FETCH_ANSWERS_SUCCESS = "FETCH_ANSWERS_SUCCESS";
export const FETCH_ANSWERS_FAILURE = "FETCH_ANSWERS_FAILURE";

export const POST_ANSWERS_REQUEST = "POST_ANSWERS_REQUEST";
export const POST_ANSWERS_SUCCESS = "POST_ANSWERS_SUCCESS";
export const POST_ANSWERS_FAILURE = "POST_ANSWERS_FAILURE";