export const FETCH_QUESTIONS_REQUEST = "FETCH_QUESTIONS_REQUEST";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE";

export const FETCH_ONE_QUESTION_REQUEST = "FETCH_ONE_QUESTION_REQUEST";
export const FETCH_ONE_QUESTION_SUCCESS = "FETCH_ONE_QUESTION_SUCCESS";
export const FETCH_ONE_QUESTION_FAILURE = "FETCH_ONE_QUESTION_FAILURE";

